notifications:
  channels: ["telegram"]   # active channels: telegram, email, whatsapp

filters:
  areas:                     # only listings in these areas; empty list means no filtering 
    - "utrecht/tuinwijk-oost"
    - "utrecht/tuinwijk-west"
    - "utrecht/vogelenbuurt"
    - "utrecht/zeeheldenbuurt-hengeveldstraat-en-omgeving"
    - "utrecht/wittevrouwen"
    - "utrecht/buiten-wittevrouwen"
    - "utrecht/wilhelminapark-en-omgeving"
    - "utrecht/oudwijk"
  price_min: 550000          # null = no lower bound
  price_max: null            # null = no upper bound
  publication_days: 3        # only listings published within this many days
  energy_labels:             # only listings with these energy labels; empty list means no filtering
    - "A++++"
    - "A+++"
    - "A++"
    - "A+"
    - "A"
    - "B"
    - "C"
    - "A+++++"          
  min_bedrooms: 1            # null = no lower bound
  keywords: []               # only listings whose description contains at least one of these keywords; empty list means no filtering

schedule:
  times_per_day: 6
  hours: ["7:00", "9:00", "12:00", "15:00", "16:15", "18:00"]